/**
 * Overlay Command: Generate and Manage Analytical Overlays
 *
 * The overlay command provides multi-dimensional perspectives on the PGC (Grounded Context Pool)
 * through specialized analytical overlays that transform raw structural data into domain-specific
 * knowledge representations.
 *
 * OVERLAYS (Cognitive Dimensions):
 * - O1: Structural Patterns (code symbols, functions, classes - built by genesis)
 * - O2: Security Guidelines (threat models, attack vectors, mitigations)
 * - O3: Mathematical Proofs (theorems, lemmas, formal verification)
 * - O4: Mission Concepts (organizational goals, principles, constraints)
 * - O5: Operational Patterns (workflows, deployment models, operational procedures)
 * - O6: Lineage (dependencies, call chains, artifact relationships)
 * - O7: Strategic Coherence (alignment between code and mission)
 *
 * WORKFLOW:
 * Each overlay is generated by querying the PGC and applying semantic analysis:
 * 1. Extract relevant items from PGC (structural symbols, documentation, etc.)
 * 2. Generate vector embeddings via workbench (eGemma)
 * 3. Apply overlay-specific filters and transformations
 * 4. Store results with metadata and coherence scores
 * 5. Index for efficient similarity search
 *
 * @example
 * // Generate security guidelines overlay
 * cognition-cli overlay generate security_guidelines --mission missions/
 *
 * @example
 * // List all available overlays
 * cognition-cli overlay list
 *
 * @example
 * // Generate multiple overlays
 * cognition-cli overlay generate operational_patterns security_guidelines
 */

import { Command } from 'commander';
import { generateCommand } from './overlay/generate.js';
import { listCommand } from './overlay/list.js';

/**
 * Command for managing and generating analytical overlays.
 *
 * Routes to subcommands:
 * - generate: Create new overlays from PGC data
 * - list: Show available overlays and their status
 */
const overlayCommand = new Command('overlay').description(
  'Manage and generate analytical overlays.'
);

overlayCommand.addCommand(generateCommand);
overlayCommand.addCommand(listCommand);

export { overlayCommand };
