#!/usr/bin/env sh
# husky

# This script is automatically generated by Husky.
# Do not edit this file directly.

if [ "$HUSKY" = "0" ]; then
  exit 0
fi

debug () {
  if [ "$HUSKY_DEBUG" = "1" ]; then
    echo "husky - $1"
  fi
}

debug "husky.sh"

# Hook arguments
hook_args="$@"

# Export hook arguments
export hook_args

# Hook directory
hook_dir="$(dirname "$0")/.."

debug "hook_dir: $hook_dir"

# Source local husky config if it exists
[ -f "$hook_dir/.huskyrc" ] && . "$hook_dir/.huskyrc"
